sudo: required

language: php

php:
  - 7

services:
  - rabbitmq

before_script:
  - phpenv config-rm xdebug.ini
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git clone https://github.com/pdezwart/php-amqp.git
  - cd php-amqp
  - phpize
  - ./configure
  - make
  - sudo make install
  - cd ..
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update
  - sudo rabbitmqctl add_vhost /humus-amqp-test
  - sudo rabbitmqctl set_permissions -p /humus-amqp-test guest ".*" ".*" ".*"
  # patching php-amqplib, see: https://github.com/php-amqplib/php-amqplib/pull/399
  - sed -i '/$message = $this->get_and_unset_message($delivery_tag);/a \ \ \ \ \ \ \ \ \ \ \ \ $message->delivery_info['delivery_tag'] = $delivery_tag;' vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php

script:
  - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --exclude-group=ssl --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_success:
  - php vendor/bin/coveralls -v
