sudo: required

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - rabbitmq

addons:
  apt:
    packages:
      - rabbitmq-server

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - sudo cp $TRAVIS_BUILD_DIR/provision/rabbitmq.config /etc/rabbitmq/
  - sudo service rabbitmq-server restart
  - git clone https://github.com/alanxz/rabbitmq-c.git
  - cd rabbitmq-c
  - git checkout v0.8.0
  - git submodule init && git submodule update
  - autoreconf -i && ./configure --prefix=$HOME/rabbitmq-c && make && make install
  - cd ..
  - git clone https://github.com/pdezwart/php-amqp.git
  - cd php-amqp
  - phpize
  - ./configure --with-librabbitmq-dir=$HOME/rabbitmq-c
  - make
  - sudo make install
  - cd ..
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES
  - sudo rabbitmqctl add_vhost /humus-amqp-test
  - sudo rabbitmqctl set_permissions -p /humus-amqp-test guest ".*" ".*" ".*"

script:
  - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --exclude-group=ssl --coverage-text --coverage-clover ./build/logs/clover.xml
  - rm -rf rabbitmq-c
  - rm -rf php-amqp
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - ./vendor/bin/docheader check bin/ config/ src/ tests/

after_success:
  - php vendor/bin/coveralls -v
